### ISSUE TITLE
Multiple size values in `sizes`?

### ISSUE THREAD

**Issue by aarongustafson** [rayankans/image-resource#1]
I know you copied it from the manifest spec, but should `sizes` actually be "a string consisting of an unordered set of unique space-separated tokens which are ASCII case-insensitive that represents the dimensions of an image"? The "space-separated" bit is the piece that throws me. An image only has one natural dimension, so supplying multiple sizes (as you would inside `img`, in concert with `srcset`) seems like it wouldn’t fit here. There is no `srcset`. The collection of `ImageResource`s is the source set. We should probably bring this up with Marcos and/or Matt as well; not sure what the original rationale was.

If we do remove the space-separated bit, it make make sense to reference the HTML `img` sizes attribute, but merely state that it can be a single acceptable size value.

Thoughts?

**Comment by dominickng** [comment]
Per the comments on w3c/manifest#807, `sizes` allows for multiple entries to support non-scalable icon files that can contain multiple discrete icons of different sizes (e.g. an `.ico` or an `.icns` file).

**Comment by rayankans** [comment]
Yeah, as @dominickng pointed out it's mostly there for `ico` icons. I also believe it can also be used for `svg` icons to include what dimensions it can be scaled to.

The Manifest spec briefly touches on that [here](https://www.w3.org/TR/appmanifest/#example-9).

**Comment by NotWoods** [comment]
`svg` icons can probably just use `"sizes": "any"` but the multiple values are still needed for `ico`.

**Comment by aarongustafson** [comment]
Ah, ok that makes sense. I forgot about the .icns container.
